### ISSUE TITLE
Error when Wallpaper commande without argument

### ISSUE THREAD

**Issue by PierrotMetille** [Compagnie-Hydromel/CompagnieHydromel#5]
Notable non-fonctionable command : 

- profile-manager buy/preview

**Comment by EthannSchneider** [comment]
2023-08-04 23:38:05.583310 [ERROR] : Traceback (most recent call last):
  File "/home/ethann/Document/BotDiscord/CompagnieHydromel/cogs/archiveuse/profile_manager.py", line 46, in profile_manager
    await ctx.respond(file=discord.File(Utils().download_image(Wallpaper(options_specifies).url()), "wallpaper.png"))
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethann/Document/BotDiscord/CompagnieHydromel/libs/databases/wallpaper.py", line 24, in __init__
    if not self.__db_access.is_wallpaper_exist(self.__wallpaper_name):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethann/Document/BotDiscord/CompagnieHydromel/libs/databases/sqlite/sqlite_access.py", line 184, in is_wallpaper_exist
    return len(self.__sqliteDB.select("SELECT name FROM wallpapers WHERE name = '" + wallpaper_name + "'")) > 0
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by EthannSchneider** [comment]
Solved on https://github.com/EthannSchneider/CompagnieHydromel/pull/6
